Fix TypeScript compile error with Electron
`WebviewTag` is no longer defined in `electron` module, fix for 
```
node_modules/electron-tabs/index.d.ts:2:9 - error TS2305: Module '"electron"' has no exported member 'WebviewTag'.

2 import {WebviewTag} from 'electron';
```